### ISSUE TITLE
Support server side blazor without server side rendering

### ISSUE THREAD

**Issue by alexandrereyes** [chanan/BlazorStyled#35]
BlazorStyled is not working when server side rendering is disabled.

My application is a server side blazor but doesn't have a cshtml file, instead, it has an index.html:

```
 app.UseEndpoints(endpoints =>
            {
                endpoints.MapBlazorHub().AddComponent(typeof(App), selector: "app");
                endpoints.MapFallbackToFile("index.html");
            });
```

So....I put `<style id="styled"></style>` inside index.html but looks like blazorStyle isn't populating any css inside this tag

**Comment by chanan** [comment]
I never tried that. I assume it would need to use the "client side syntax" to work.

Can you supply a small project that I can try this on?

**Comment by VR-Architect** [comment]
Are you using Syncfusion by chance? I upgrade to today's version for both.

Syncfusion needs this to work:
`endpoints.MapBlazorHub<App>(selector: "app");`

BlazorStyled needs this to work:
`endpoints.MapBlazorHub();`

How to get both to work together?

**Comment by chanan** [comment]
No, I have tried Synfusion, I **think** that if you use mine Syncfusion will work as well. Have you tried that?

**Comment by alexandrereyes** [comment]
[repo.zip](https://github.com/chanan/BlazorStyled/files/3522857/repo.zip)
@chanan here is the project witch reproduces the problem

**Comment by chanan** [comment]
I will take a look at this evening. Thanks for putting that together

**Comment by chanan** [comment]
@alexandrereyes Yes, the one you sent will not currently work (server side pre render) - I do plan to keep trying to work on it, but figured it might be better to wait for an RC of Blazor (should be soon) before trying too hard due to changes in the way Blazor works (Preview8 is what actually broke this). In case you don't have a working Server Side project at all, I fixed the project (i.e. took off pre rendering) and posted it at: https://github.com/chanan/BlazorStyledIssue <--- this is a server side project with BlazorStyled ready to go.

**Comment by chanan** [comment]
@alexandrereyes & @VR-Architect - I added a sample called ServerPreRenderSample: https://github.com/chanan/BlazorStyled/tree/master/src/ServerSidePreRender

Does this do what you two want?

**Comment by chanan** [comment]
I think this works now, let me know if you guys run into other issues
