### ISSUE TITLE
Is Blazor.ServerSideStyled obsolete?

### ISSUE THREAD

**Issue by DataJuggler** [chanan/BlazorStyled#72]
I updated a project today and this line stopped compiling. Is it no longer needed? 

@(await Html.RenderComponentAsync<BlazorStyled.ServerSideStyled>(RenderMode.ServerPrerendered))

Thanks, I didn't see a new features for 2.0/2.1 versions, do you have that posted anywhere?

Thanks,

Corby

**Comment by niem94** [comment]
Yes it is :-)

You can safely delete that line. BlazorStyled only needs  services.AddBlazorStyled(); from 2.0 and up.

**Comment by chanan** [comment]
That’s correct no longer needed. 

I am on mobile right so hard to list here but if you check the releases link on the main github page and go to 2.0.0 you should see it. The main new thing is a whole new underpinning of the project so you no longer need that tag in the head. 

Another thing is kind of minor but helpful, when you compose classes it will compose class names instead of the styles, and also allows you to put rules in the Styled being composed where before you couldn’t.

**Comment by DataJuggler** [comment]
I took it out and it compiled. Good to know, easier is always better out of the box.

Thanks

**Comment by chanan** [comment]
I am going to add a section to the doc sites with the release notes over the weekend, so hopefully going forward this will be mitigated. 

Closing this issue since I think everyone is up and working now.
