### ISSUE TITLE
[Question] How do you modify the body tag?

### ISSUE THREAD

**Issue by ofrades** [chanan/BlazorStyled#92]
Can you explain how do you managed to have the dark/light mode in your samples working? Is something to do with changing the body tag?

**Comment by chanan** [comment]
The theme switcher works using BlazorStyled themes. Yes, it changes the body tag. Here are the relevant sections of code:

In MainLayout.cs https://github.com/chanan/BlazorStyled/blob/master/src/SampleCore/Shared/MainLayout.razor#L10-L24

```
<Styled>
            html {
                color: [colors.text-color];
            }
            body {
                background-color: [colors.background-color];
                color: [colors.text-color];
            }
            p {
                color: [colors.text-color];
            }
            hr {
                background-color: [colors.hr];
            }
</Styled>
```

Those are the styles I am changing. There is another one later done the file for p > code.

In the same file https://github.com/chanan/BlazorStyled/blob/master/src/SampleCore/Shared/MainLayout.razor#L166-L174 I setup the initial colors:

```
protected override void OnInitialized()
    {
        //Setup default theme (light)
        Styled.SetThemeValue("colors.background-color", "#f0f0f0");
        Styled.SetThemeValue("colors.text-color", "#994cc3");
        Styled.SetThemeValue("colors.code-background", "rgba(117,63,131,0.07)");
        Styled.SetThemeValue("colors.code-text", "#1B1D1D");
        Styled.SetThemeValue("colors.hr", "hsla(0,0%,0%,0.2)");
    }
```

That default the theme to the light theme (Note: An enhancement I wanted to do but never got around to doing is to use the new CSS `prefers-color-scheme` to show light or dark theme based on the user's OS setting).

In https://github.com/chanan/BlazorStyled/blob/master/src/SampleCore/Shared/Toggle.razor#L87-L112 the OnChange of the toggle switches between the two themes:

```
private void OnChange(ChangeEventArgs e)
    {
        bChecked = !bChecked;

        if(bChecked)
        {
            //Setup dark theme
            Styled.SetThemeValue("colors.background-color", "#011627");
            Styled.SetThemeValue("colors.text-color", "#82AAFF");
            Styled.SetThemeValue("colors.code-background", "#263238");
            Styled.SetThemeValue("colors.code-text", "#C792EA");
            Styled.SetThemeValue("colors.hr", "#4e6699");
            DefaultSettings.DefaultTheme = "https://raw.githubusercontent.com/chanan/BlazorPrettyCode/master/src/BlazorPrettyCode/wwwroot/WinterIsComingDark.json";
        }
        else
        {
            //Setup light theme
            Styled.SetThemeValue("colors.background-color", "#f0f0f0");
            Styled.SetThemeValue("colors.text-color", "#994cc3");
            Styled.SetThemeValue("colors.code-background", "rgba(117,63,131,0.07)");
            Styled.SetThemeValue("colors.code-text", "#1B1D1D");
            Styled.SetThemeValue("colors.hr", "hsla(0,0%,0%,0.2)");
            DefaultSettings.DefaultTheme = "PrettyCodeDefault";
        }
        StateHasChanged();
    }
```

This code can be enhanced by BlazorStyled to allow the user to save theme names instead of changing each value every time and to be able to do it with a Tag instead of the API. I have a Feature issue for that: #78

**Comment by ofrades** [comment]
Thanks and congrats on the very nice library.

**Comment by ofrades** [comment]
Can I use it with other libraries like BlazorStrap? And if so how do the styles using BlazorStyled override the one coming from BlazorStrap, which I think in the bottom are using the bootstrap cdn?

I am able to dynamically change the background but when using it mixed with the bootstrap cdn nothing happens because the bootstrap cdn have priority somehow.

**Comment by ofrades** [comment]
```
    body {
        background-color: [colors.background-color] !important;
        color: [colors.text-color] !important;
    }
```

**Comment by chanan** [comment]
Yes, you can use BlazorStyled with BlazorStrap (or any other library). In fact if you look at https://blazorstrap.io - the code snippets is done with BlazorStyled, specifically using BlazorPrettyCode (I am not very good naming things).

**Comment by imtrobin** [comment]
Ok, I have follow up question. If I want to add another class, like this 

```
MainLayout.razor
<Styled>
   ..
    XXX { color: [colors.xxx-color] !important;
</Styled>

ThemeSelector.razor
..
Styled.SetThemeValue ("colors.xxx-color"] = red;


Another .razor
<p class=XXX >XXXTest </p>

```
XXXTest color should be from red, right? But it's not working.
