### ISSUE TITLE
Slow CSS after reloading.

### ISSUE THREAD

**Issue by Deckweiss** [chanan/BlazorStyled#98]
I tried using BlazorStyled to have a clearer thought process and workflow so far, but I'd like to keep using it so that I can easily parameterize things such as background color etc. for reusable elements. So far there is a huge delay between the page load and the css being applied to the components. 
Video example: https://gofile.io/d/SiaFXq
Note how there are multiple steps of the css being loaded in, first there is none, then you see the label box and the yellow content box (which is hidden by default), then the content box gets hidden away and the next element starts loading.

I think it might be related to issue https://github.com/chanan/BlazorStyled/issues/3 but that issue is all over the place topic wise, so I wasn't sure and decided to open a new one.

I am even unsure if this is really BlazorStyled fault, this is a Blazor server-side app running in debug/development mode and the component is using js interop for a clean animation with variable content heights. Style composition is used as per the examples on your website.

Is there any way to optimize this?
Any help and suggestions are welcome.

Thanks and cheers.

**Comment by Deckweiss** [comment]
ExpandableInfoBox.razor

```
@namespace ComponentLibrary.Shared.Examples
@inject IJSRuntime JsRuntime

<Styled @bind-Classname="@labelToggle">
    display: block;
    text-align: left;
    padding: 1rem;
    margin-left: 6px;
    margin-right: 6px;
    margin-top: 6px;
    margin-bottom: 0px;
    color: #000000;
    background: #F0F0F0;
    cursor: pointer;
    border-radius: 3px;
    transition: all 0.25s ease-out;
</Styled>

<Styled Classname="@labelToggle" PseudoClass="PseudoClasses.Hover">
    background: #DDDDDD;
</Styled>

<Styled @bind-Classname="@contentInner">
    background: rgba(250, 224, 66, .2);
    border-bottom: 1px solid rgba(250, 224, 66, .45);
    border-bottom-left-radius: 3px;
    border-bottom-right-radius: 3px;
    padding: .5rem 1rem;
    margin-left: 6px;
    margin-right: 6px;
</Styled>

<Styled @bind-Classname="@expanded">
    max-height: @MaxHeight;
    transition: max-height 1s ease-in-out;
</Styled>

<Styled @bind-Classname="@contentOuter" ComposeExpanded="@expanded" ComposeExpandedIf="@IsExpanded">
    overflow: hidden;
    max-height: 0px;
    transition: max-height 1s ease-in-out;
</Styled>

<Styled @bind-Classname="@rotated">
    transform: rotate(90deg);
</Styled>

<Styled @bind-Classname="@triangle" ComposeRotated="@rotated" ComposeRotatedIf="@IsExpanded">
    content: ' ';
    display: inline-block;
    border-top: 5px solid transparent;
    border-bottom: 5px solid transparent;
    border-left: 5px solid currentColor;
    vertical-align: middle;
    margin-right: .7rem;
    margin-bottom: .3rem;
    transition: transform 1s ease-in-out;
</Styled>

<div>
    <label class="@labelToggle" @onclick="Toggle">
        <div class="@triangle"></div>
        @LabelText
    </label>
    <div class="@contentOuter" @ref="collapsibleContent">
        <div class="@contentInner">
            @ChildContent
        </div>
    </div>
</div>

@code {

    private string labelToggle, contentOuter, contentInner, expanded, triangle, rotated;
    ElementReference collapsibleContent; //html reference for passing to js
    [Parameter]
    public string MaxHeight { get; set; }
    [Parameter]
    public Boolean IsExpanded { get; set; }

    [Parameter]
    public string LabelText { get; set; }
    [Parameter]
    public RenderFragment ChildContent { get; set; }

    async Task Toggle()
    {
        if (MaxHeight != null)
        {
            MaxHeight = null;
            IsExpanded = false;
        }
        else
        {
            var scrollHeight = await JsRuntime.InvokeAsync<float>("getScrollHeight", collapsibleContent);
            MaxHeight = scrollHeight + "px";
            IsExpanded = true;
        }
    //StateHasChanged();
    }
}
```

utilities.js

```
function getScrollHeight(element) {
    return element.scrollHeight;
}
```

Example use of the component:

```
<ExpandableInfoBox LabelText="This is the title">
    <p>Here you can put any content</p>
    <p>The content will be visible when the box is expanded </p>
</ExpandableInfoBox>
```

**Comment by chanan** [comment]
Hi,

Thanks for using BlazorStyled!

Here are a few tips:

1. First of all, update to v3 when it gets released in a hour or so. I did a lot of work on allocations which will help speed up BlazorStyled especially in WASM mode. I plan to keep this work up in the following weeks in months
2. Make sure you are running in development: false when looking at speed, it should be slightly faster (Version 2.x ignored this argument, but version 3 uses it again)
3. The `<Styled />` is nice to use but it is always going to be slower then using `IStyled` directly, this is because the tag has to "translate" the `RenderFragment` to a string that gets passed to `IStyled`
4. Lastly, when using `IStyled` directly you can ensure it only occurs once (unless the string changes) for example, if you are know the css won't change you can put it inside of `OnAfterRenderAsync` with an `if(firstRender)`

Just in case anyone reads this that doesn't need these optimizations - using `<Styled />` is perfectly fine in most cases, and indeed, it too has some optimizations regarding re-running the same css again if it hasn't changed, so only use the tips above if you know you need them.

One last thing, there is a measurable amount of time to go between .NET and javascript via the IJSInterop. @lupusa1 (on twitter) mentioned there is a trick to greatly speed that up, but I haven't had time to look into yet.

**Comment by Deckweiss** [comment]
I forgot to mention - I am using 3.0.0-alpha-07

Can you elaborate a bit on point 2. ? Does it mean that speed of the app is significantly different and in the order of published > development > debug. Or am I misunderstanding something?

Thanks again for taking time and your amazing work!

**Comment by chanan** [comment]
There are two variables you pass it to `AddBlazorStyled()`

- debug: true/false - when true, it will out some console.log info to the DevTools console. Set this false in prod.
- development true/false - when true, BlazorStyled will output your css as a "string" between a `<style>...</style>` tag in the head. When false, it uses `insertRule` on `<style />` (https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule) which is much faster especially if you have lots of styles.

One thing to note is that when you use `insertRule` the styles become "read only" in DevTools, and you can't edit them on the fly using DevTools, which is why `development: true` exists.

**Comment by Deckweiss** [comment]
When running with `development: false` it is significantly faster. But you still see all the loading steps (maybe for just one frame). But I think I what also contributes greatly to the inconsistent look is the transition that gets applied when the css gets added - which makes the element look like it is growing.

When taking the transition out of the css, you can still see the process of the css getting applied, but it only takes a fracture of a second, which is much better than my original example video showed.

I think I would try using IStyled when I have some more time, but it is not nice for the developer I think. It reminds me of java swing, where there is no MVC and the definition of the looks is jumbled up with the logic.

**Comment by chanan** [comment]
When more thing you can try to help with that is to hide your div till the CSS is loaded. I started adding that directly into `BlazorStyled` but haven't gotten it right yet since it is very dependent on the actual situation and doesnt always work right (Transitions is one of those that might not work). Here is an example:

1. in razor page: https://github.com/chanan/BlazorSlides/blob/master/src/BlazorSlides/Slides.razor#L2 look at the style attribute
2. In the code behind it is set to visibility hidden: https://github.com/chanan/BlazorSlides/blob/master/src/BlazorSlides/Slides.razor.cs#L22
3. In the same file in the `OnAfterRenderAsync`: https://github.com/chanan/BlazorSlides/blob/master/src/BlazorSlides/Slides.razor.cs#L82-L102 - you can see on line 98 it removes the visibility hidden.

It's not a perfect solution, and I think I actually have a better version that I didnt upload to Github, but can't check right now, working on the V3 release :)

**Comment by Deckweiss** [comment]
Thanks for the great pointers, I think I can work with that, I was thinking about adding a loading screen anyway and this approach seems perfect for that.

I wish you success with the release!

**Comment by Deckweiss** [comment]
Here is a video showing the comparison between how it was before and after adding the loading screen workaround https://gofile.io/d/t2zPLC

I had to use `await Task.Delay(600);` in the OnAfterRenderAsync Task. 
It is not a very neat solution, because I use a hard coded delay, so that the transition animation would stop playing. But so far I am happy with this workaround.
